set_property IOSTANDARD LVCMOS33 [get_ports CLK_100MHz]
set_property PACKAGE_PIN E3 [get_ports CLK_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_DREQ]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_xDCS]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_xCS]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_xRSET]
set_property PACKAGE_PIN K1 [get_ports MP3_xDCS]
set_property PACKAGE_PIN F6 [get_ports MP3_xRSET]
set_property PACKAGE_PIN J2 [get_ports MP3_DREQ]
set_property PACKAGE_PIN E7 [get_ports MP3_xCS]
set_property PACKAGE_PIN J3 [get_ports MP3_SCLK]
set_property PACKAGE_PIN J4 [get_ports MP3_MOSI]

set_property IOSTANDARD LVCMOS33 [get_ports IS_SUSPENDING]
set_property PACKAGE_PIN H17 [get_ports IS_SUSPENDING]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_LASTSONG]
set_property PACKAGE_PIN P17 [get_ports MP3_LASTSONG]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_NEXTSONG]
set_property PACKAGE_PIN M17 [get_ports MP3_NEXTSONG]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_VOL_DOWN]
set_property PACKAGE_PIN P18 [get_ports MP3_VOL_DOWN]
set_property IOSTANDARD LVCMOS33 [get_ports MP3_VOL_UP]
set_property PACKAGE_PIN M18 [get_ports MP3_VOL_UP]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property PACKAGE_PIN J15 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports SUSPEND]
set_property PACKAGE_PIN N17 [get_ports SUSPEND]

set_property IOSTANDARD LVCMOS33 [get_ports IS_SONG0]
set_property IOSTANDARD LVCMOS33 [get_ports IS_SONG1]
set_property IOSTANDARD LVCMOS33 [get_ports IS_SONG2]
set_property PACKAGE_PIN V11 [get_ports IS_SONG0]
set_property PACKAGE_PIN V12 [get_ports IS_SONG1]
set_property PACKAGE_PIN V14 [get_ports IS_SONG2]

set_property IOSTANDARD LVCMOS33 [get_ports OLED_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports OLED_CS]
set_property IOSTANDARD LVCMOS33 [get_ports OLED_DIN]
set_property IOSTANDARD LVCMOS33 [get_ports OLED_RES]
set_property IOSTANDARD LVCMOS33 [get_ports OLED_D_C]
set_property PACKAGE_PIN C17 [get_ports OLED_CLK]
set_property PACKAGE_PIN D18 [get_ports OLED_CS]
set_property PACKAGE_PIN E18 [get_ports OLED_D_C]
set_property PACKAGE_PIN D17 [get_ports OLED_DIN]
set_property PACKAGE_PIN G17 [get_ports OLED_RES]


